WooCommerce : Add support for fetching custom order stats
wordpress-mobile/WordPress-FluxC-Android pull request #1103
Opened 2019-02-05 06:47 UTC by anitaa1990

Fixes #1007 

This PR adds the following:

* Provides option to pass date range when fetching order/revenue stats
* Calculates quantity (how far back to go), based on the date range and the granularity before passing it to server api. If no date range is passed, default/static values are used.
* Parses and caches the response in the db - including the quantity and date.
*  Unit tests and mock tests included. (Added in `WCStatsStoreTest`)
* Also includes 2 new buttons on the **Woo** screen of the **example** app: **FETCH CUSTOM REVENUE STATS** and **FETCH CUSTOM REVENUE STATS (FORCED)**

<img src="https://user-images.githubusercontent.com/22608780/52257088-40e5ef00-293f-11e9-8bd1-20c56e8400a2.png" width="300"/>

<img src="https://user-images.githubusercontent.com/22608780/52913540-1738aa80-32e5-11e9-87f5-58f3c6e2b81d.png" width="300"/>

## Testing Notes
*  This feature includes an alteration to existing db table: `WCOrderStatsModel` - App upgrade testing to be done as well.

**Note** Changes need to be added to the front end as well to utilise this feature in WCAndroid.

2019-02-06 01:06 UTC, AmandaRiu reviewed
@anitaa1990  very nice work. I left some small lower priority comments in the code, but the overall logic looks great. I played around with the buttons in the example app, that looks good. Could you add some logic to remember the last selection in the custom stats dialog? Not a big deal, will just make testing easier.

I ran out of time to really dig into the code as much as I would like to, but I did review the code changes and play with the example app and on this first pass it looks great. Nice attention to detail and your code is very clean. My only suggestion is to make sure you run the `a8c style` checkstyle config on the project after you make changes, as well as `./gradlew ktlint` from the command line. I'll do a more in-depth review tomorrow and submit more feedback once the small suggested fixes have been submitted.

2019-02-06 04:39 UTC, anitaa1990 commented on fluxc/src/main/java/org/wordpress/android/fluxc/utils/SiteUtils.java
> +    public static Date getDateFromString(String dateString) {
Ahh your're right! Will do that!

2019-02-06 04:41 UTC, anitaa1990 commented on fluxc/src/main/java/org/wordpress/android/fluxc/utils/SiteUtils.java
> +
Yup:) Actually, noticed that when I created PR, the CI build was failing because of this so added [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103/commits/07269b35d16c49dc6c3d579145477b066fdadcb0) to fix it

2019-02-06 04:41 UTC, anitaa1990 commented on fluxc/src/main/java/org/wordpress/android/fluxc/utils/SiteUtils.java
> +     *
Yup:) Actually, noticed that when I created PR, the CI build was failing because of this so added [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103/commits/07269b35d16c49dc6c3d579145477b066fdadcb0) to fix it

2019-02-06 12:43 UTC, anitaa1990 commented on fluxc/src/main/java/org/wordpress/android/fluxc/utils/SiteUtils.java
> +    public static Date getDateFromString(String dateString) {
Moved the methods to a separate class in this [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103/commits/ef8d9e3b20b5ccca8eed32715152c5f024a754b3)

2019-02-11 11:44 UTC, anitaa1990 commented
@AmandaRiu as per our discussion, I added the startDate to sqlite. I also added the `endDate` field as well. Even though we are storing the end date field (this was formatted based on the granularity - so if WEEKS were selected, then the date would be stored in yyyy-'W'ww format). Since this would not accurately display the end date the user has selected, I had added this field as well.

Please review :) 

I also want to add that: I think there have been some changes to the `WellSqlConfig.java` class. When I started development, the db version was 52. I think it has changed to 54. So when merging with the develop branch, we would need to modify the class to update our changes from this branch as well.

2019-02-12 06:16 UTC, anitaa1990 commented
@AmandaRiu merged with the latest changes in develop branch and resolved the conflicts. Please review :)

2019-02-13 01:01 UTC, AmandaRiu requested changes
@anitaa1990 This is looking great! I do have several code comments in addition to items noted below. In the code comments, "np" is our shortened code for "nitpick" which basically means it's a really low-priority comment and more of a suggestion than anything else. Typically if a reviewer adds a nitpick, we implement the suggestion unless we feel very strongly that it shouldn't be implemented. 

Here are some other things I found during my review:
- The date selector dialog remembers the selected dates, but once you select a date in the past, you can't go forward on the calendar. Also, when you open the calendar again, the selected date is off by a month.
<img src="https://user-images.githubusercontent.com/5810477/52678784-e16c7e00-2f00-11e9-8a1e-9051fc9932db.gif" width="300"/>

- Date selector loses selection if left open while switching apps, and then doesn't register changes (probably because the listener will be gone) -- to test - make sure "DON'T KEEP ACTIVITIES" is toggled on in device developer options. 
<img src="https://user-images.githubusercontent.com/5810477/52678819-f0ebc700-2f00-11e9-8c4f-6e818af01380.gif" width="300"/>

- 30 days comparison w/ standard stats: the end date ends up one day different (selecting a start date of 1/14 and 30 days):
	- standard: 2/12
	- custom: 2/11
- custom ranges for fetching visitor stats is not included yet. This will be needed for the card in the UI.

2019-02-14 10:41 UTC, anitaa1990 commented on example/src/main/java/org/wordpress/android/fluxc/example/WooCommerceFragment.kt
> +                    } ?: run {
I added a new field to the `OnWCStatsChanged` class, to differentiate between custom stats and default stats. So modified logic based on this.

2019-02-14 10:44 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt
> +                getFormattedDate(payload.site, payload.granularity, payload.endDate),
:) got it! Modified this and all corresponding methods to increase readability

2019-02-14 10:46 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCStatsSqlUtils.kt
> +    fun insertOrUpdateOrderStats(stats: WCOrderStatsModel): Int {
Yeah, makes sense to remove the new method and add the updated logic to the old method. Also `event.date` is never null since the date from the server api is never null. So added a new field  `event.isCustomField` to differentiate between default and custom stats

2019-02-14 10:49 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/WCStatsSqlUtils.kt
> +            return getRawStatsForSiteAndUnit(site, unit)
Based on this logic, I've modified all the queries to include `IS_CUSTOM` - since as you said if custom stats has the same date range and unit as default stat, then it would unintentionally return custom stat instead of default stat.

2019-02-14 10:49 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.java
> +
👍 Modified this as well!

2019-02-14 10:49 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.java
> +    public static long getQuantityInMonths(@NonNull Calendar c1,
Makes sense! Converted this class to kotlin and added some more test cases for the methods

2019-02-14 10:50 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.java
> +    public static @NonNull String getDateTimeForSite(@NonNull SiteModel site,
👍

2019-02-14 10:50 UTC, anitaa1990 commented on example/src/main/res/layout/dialog_custom_stats.xml
> +
👍

2019-02-14 10:51 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.java
> +public class DateUtils {
👍 Modified it to kotlin and added test cases as well

2019-02-15 18:11 UTC, AmandaRiu requested changes
@anitaa1990 Nice work on this PR...it's almost ready! Just a few more items to address:
- I see you added support for custom visitor stats, but I don't see a button in the example app to test the custom visitor stats.
- The custom date range selector dialog does not scroll. This is needed when in landscape mode:
<img src="https://user-images.githubusercontent.com/5810477/52875451-62ef2680-3122-11e9-9398-0732a063643d.png" width="300"/>
- Date selector being off by a month is fixed, but I'm seeing some strange behavior when the selected date is the last day of the month:
<img src="https://user-images.githubusercontent.com/5810477/52875564-9d58c380-3122-11e9-9b27-668e3857e218.gif" width="300"/>
- Please also see code comments.

2019-02-15 18:41 UTC, AmandaRiu commented
@anitaa1990 I've created a matching branch in our FluxC repository and will merge this PR into that branch once you address my last review. This will make it easier for us to test going forward because once this is merged we can just use the commit hash in the WCAndroid code directly.

2019-02-17 11:23 UTC, anitaa1990 commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.kt
> +        calendar.add(Calendar.SECOND, currentDate.seconds)
Sure. I added a calendar instance instead to get the hours, minutes and seconds. You can checkout this [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103/commits/810349f9fd6879596369f7b39bb6ab025fd3ba96).  

The commit also includes the changes to the date utils class - this was originally in the sample app but since we use the same utils to display in both sample and woocommerce app, I migrated it to the DateUtils class. Fixed the strange behaviour of date selector as well - when last date of month was selected. I added test cases to test all dates from 2011 till present.

2019-02-18 04:46 UTC, anitaa1990 commented
> I see you added support for custom visitor stats, but I don't see a button in the example app to test the custom visitor stats.
Hi @AmandaRiu , this has actually been on my TODO list. I have added 2 buttons * on the **Woo** screen of the **example** app to * **FETCH CUSTOM VISITOR STATS** and **FETCH CUSTOM VISITOR STATS (FORCED)**. There are a couple of clarifications to the implementation though:
* The date selection for visitor stats is not remembered. For order stats, the date selection is stored in FluxC. But for visitor stats, since this functionality is not needed in FluxC, I thought of adding the visitor date selection and granularity in SharedPreferences and displaying that.
* Unlike `FetchOrderStatsResponsePayload`, `FetchVisitorStatsResponsePayload` does not include the `startDate` and `endDate` selected by user. So when the `FETCH_VISITOR_STATS` event is fired, the sample app will not display the date selected by the user in the logs. But without this there is no differentiation between the default visitor stats and the custom stats. So I thought of including the `date`, `quantity` and `isCustomField` for `FETCH_VISITOR_STATS` as well. This feature will not be used at the moment in the WooCommerce app but in the example app, we would be able to differentiate between the custom and default visitor stats. 

> The custom date range selector dialog does not scroll. This is needed when in landscape mode
This is added in this [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103/commits/12ca7c88ad58bc86a1a88d57d349e6538db907bf)

> Date selector being off by a month is fixed, but I'm seeing some strange behavior when the selected date is the last day of the month
This [commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103/commits/810349f9fd6879596369f7b39bb6ab025fd3ba96) includes the changes to the date utils class - this was originally in the sample app but since we use the same utils to display in both sample and woocommerce app, I migrated it to the DateUtils class. Fixed the strange behaviour of date selector as well - when last date of month was selected. I added test cases to test all dates from 2011 till present.

2019-02-18 23:10 UTC, AmandaRiu approved these changes
@anitaa1990 This looks great! There are a few things I'll make notes on in a new PR after this is merged into the repo branch I had previously talked about, but overall, we're ready to move it under the FluxC umbrella!

2019-02-18 23:10 UTC, AmandaRiu commented on example/src/main/java/org/wordpress/android/fluxc/example/CustomStatsDialog.kt
> +            val startDate = wcOrderStatsModel?.startDate ?: DateUtils.getCurrentDateString()
It was a really good call moving these utilities into the main `DateUtils` class. 👍

2019-02-18 23:10 UTC, merged

2019-02-19 02:29 UTC, AmandaRiu commented
@anitaa1990 For the visitor stats code: I recommend removing anything that was added to the Payload specifically for the example qpp that wouldn't be used by the main app since it's just extra baggage. The visitor api calls all use caching at the HTTP level so if the parameters are the same, it will just automatically use the matching response. I also recommend removing the code for shared preferences. For the example app, just having the date ranges cached for the _active session_ is enough. Does that sound good? 

The rest all looks really good 👍 

You may need to create a new PR to merge into my `anitaa/support_custom_order_stats ` branch up on FluxC for these changes so I can merge them into our current branch since I don't believe you have access to edit that PR or branch directly (although you are welcome to try).

2022-08-11 11:33 UTC, ParaskP7 commented
👋 @anitaa1990 @AmandaRiu !

It's been 3,5 years already, I know... 😅 But, let me ask you this millisecond related question below, just in case you still remember the answer. 🤞 

As part of [this Detekt related issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2486) that I am currently working on, I am trying to resolve the `MagicNumber` related warnings. To that end, I stumbled upon this `1` warning, on the `plugins:woocommerce` module, that is related to this [DateUtils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.kt) class that you both worked on (see [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/DateUtils.kt#L103)) and was wondering about it. Was there a reason you used the `59` instead of `999` for the millisecond value there? 🤔