Create Store Attribute base endpoints handling
wordpress-mobile/WordPress-FluxC-Android pull request #1803
Opened 2020-12-16 04:37 UTC by ThomazFB

Summary
==========

*Tests coverage on upcoming PRs*

Changelog
==========
| Description | Commit |
| ------------- | ------------- |
|  |  |

Screenshots & How to Test
==========
|  | 
| ------------- | ------------- | ------------- |
|  |  |  |

2020-12-22 15:54 UTC, AmandaRiu requested changes
@ThomazFB Really nice work on this. I especially love the output in the Example app - very detailed and nicely formatted for viewing. I did find some issues with the test in the Example app though. For example, I can update an attribute and get an error, but the example app treats it like it’s successful. The Update, Create and Delete options all act like the action was successful even when there is an error response from the API. To reproduce:
1. Click **UPDATE ATTRIBUTE**
2. Leave the first dialog blank
3. Leave the second dialog blank. Flipper shows the response is a 404, but the UI shows “Attribute Updated” and doesn’t display an error. 

Also left a couple code comments for your review.

2020-12-22 15:54 UTC, AmandaRiu commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/JetpackRequestBuilderExt.kt
> +suspend fun <T : Any> JetpackTunnelGsonRequestBuilder.syncPutRequest(
Curious why you didn't just add these to the `JetpackTunnelGsonRequestBuilder` directly? It doesn't seem like much is gained by moving it into an Extension file.

2020-12-22 15:54 UTC, AmandaRiu commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCProductAttributesStore.kt
> +                        "slug" to name,
The user has the ability to create a custom slug in `wp-admin`, curious why we aren't allowing that option on the backend?

2020-12-23 15:33 UTC, ThomazFB commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/JetpackRequestBuilderExt.kt
> +suspend fun <T : Any> JetpackTunnelGsonRequestBuilder.syncPutRequest(
Well, that's something I'm curious about your opinion. The main reason I did that was related to the module distribution on FluxC, since the Woo codebase is on a different module I understood that adding functions directly to the class would insert code that is never used or required by any part inside the FluxC module, instead, it would be only used on the Woo plugin module part, so I decided to make it as an extension operation exclusive to Woo. But I'm not sure if we want to keep this kind of consistency around the entire FluxC lib. Do you think it would be better to just move everything to the FluxC module side?

2020-12-23 15:34 UTC, ThomazFB commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCProductAttributesStore.kt
> +                        "slug" to name,
Oops, nice catch! That was a mistake of mine, it's fixed on https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1803/commits/b26e1033957220e7f407093bb2cb1fabe8294827

2020-12-23 15:34 UTC, ThomazFB commented
Hey @AmandaRiu, thank you so much for your review, about the error handling and logging, I've improved it right here: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1803/commits/da0a3543aceb44ec88e6de4dc62362e234e21419. Let me know what you think!

2020-12-23 16:38 UTC, AmandaRiu commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/JetpackRequestBuilderExt.kt
> +suspend fun <T : Any> JetpackTunnelGsonRequestBuilder.syncPutRequest(
yeah I understand your point, but these methods would be used eventually and I can see a scenario where the logic ends up getting duplicated.

2020-12-23 17:42 UTC, AmandaRiu approved these changes
Looks like all the requested changes have been made. :shipit:

2020-12-23 17:43 UTC, merged