Add Stock photo caption and include it when uploading a photo
wordpress-mobile/WordPress-FluxC-Android pull request #1846
Opened 2021-01-20 13:49 UTC by fluiddot

Related to: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1609

## Description

Parse `caption` field from the response of Stock media search requests and add it to the Stock media model and item. This field is now also included in the payload when a photo is uploaded.

## Test
The changes can be tested in two different flows.

### Media screen
1. Go to a site.
2. Tap on `Media` button.
3. Tap on `+` button.
4. Tap on `Choose from Free Photo Library`
5. Search any term.
6. Tap one or multiple photos.
7. Tap on ✔️ button.
8. Wait for the items to be uploaded.
9. [Back in the Media screen] Tap on any of the recently uploaded photos.
10. Check that `Caption` field has value.

_Note: It's possible that in some cases the item doesn't have a caption value with the credit/attribution of the photo. In this case try another one._

### Image block
1. Go to a site.
2. Open a post/page.
3. Tap on `+` button.
4. Tap on `Image` block.
5. Tap on `ADD IMAGE`.
6. Tap on `Choose from Free Photo Library`
7. Search any term.
8. Tap one photo.
9. Tap on ✔️ button.
10. Wait for the item to be uploaded.
11. Check that below the photo the caption field has a value.

_Note: It's possible that in some cases the item doesn't have a caption value with the credit/attribution of the photo. In this case try another one._

2021-01-21 03:07 UTC, jd-alexander commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/stockmedia/SearchStockMediaResponse.kt
> +         * Guid property needs to be manually parsed to object because comes in String format
What do you think about rephrasing this a bit? Example : 
```suggestion
         * The GUID property needs to be manually parsed to a JSON object because it was originally deserialized as a string property.
```

2021-01-21 03:25 UTC, jd-alexander requested changes
Looks good @fluiddot I checked the code including the tests and all is well. I left a comment you can check out as well. Once that's resolved we can LGTM this.

2021-01-21 09:40 UTC, fluiddot commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/stockmedia/SearchStockMediaResponse.kt
> +         * Guid property needs to be manually parsed to object because comes in String format
I agree, your description is way clearer, thanks Joel for the feedback!

2021-01-21 18:16 UTC, jd-alexander approved these changes
Thanks for these changes @fluiddot We are good to go! LGTM 🚢

2021-02-02 00:57 UTC, jd-alexander commented
@fluiddot there's a conflict here that will require resolution :)

2021-02-02 17:01 UTC, fluiddot commented
> @fluiddot there's a conflict here that will require resolution :)

Thanks @jd-alexander for raising the issue, I've just solved the conflict in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1846/commits/f2e5d1094bb4dfc4752e22a014a1965cba66a03f.

2023-12-01 17:16 UTC, closed without merging