Order status optimistic update
wordpress-mobile/WordPress-FluxC-Android pull request #2052
Opened 2021-07-09 16:24 UTC by wzieba

For details what's an optimistic update please check https://github.com/woocommerce/woocommerce-android/issues/4248

TLDR; we update local state (in our case database) and propagate this change to the presentation layer. In case of error - we revert this change and propagate event again.

Closes: #2050

2021-07-09 16:37 UTC, wzieba commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt
> +        orderToUpdate: WCOrderModel,
The reason for this signature change is that I believe we should aim to design our APIs in a way that it's imposible or at least very difficult to model an invalid state.

`localOrderId` and `remoteOrderId` are not needed to be separated, it's quite easy to call this method with ids that both won't match the same order. So I think it's better to just pass `WCOrderModel` here.

Ideally, I'd love to not pass `SiteModel` as `WCOrderModel` can point precisely to the `SiteModel` (it's functional dependant) but I would have to refer to the database in `OrderRestClient` which would violate layers separation.

2021-07-09 16:37 UTC, wzieba commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/OrderSqlUtils.kt
> +                    .first()
There's already a method `OrderSqlUtils#getOrderForIdSet` but it accepts `OrderIdSet` as an argument. I've preferred to get the order by it's primary key, which is `WCOrderModelTable.ID`.

For a context of why `OrderIdSet` has been introduced, please see https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/800

2021-07-09 16:37 UTC, wzieba commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt
> +            wcOrderRestClient.updateOrderStatus(payload.order, site, status)
This is a core change for this PR. Update order status local database, emit a change and the perform update on remote.

2021-07-13 11:03 UTC, kidinov requested changes
Looks good! Just a minor question

2021-07-13 11:03 UTC, kidinov commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/OrderSqlUtils.kt
> +    fun getOrder(localOrderId: Int): WCOrderModel =
Not sure what convention is there, but looking into other methods it might be called `getOrderByLocalId` maybe?

2021-07-14 15:38 UTC, wzieba commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/OrderSqlUtils.kt
> +    fun getOrder(localOrderId: Int): WCOrderModel =
Good note, thanks! Renamed in 5198266. 

Just a friendly reminder: please don't merge this PR until woocommerce/woocommerce-android#4394 is approved.

Thanks for review!

2021-07-15 08:27 UTC, kidinov approved these changes

2021-07-20 09:25 UTC, merged