Update the PostModel table with the field "sticky"
wordpress-mobile/WordPress-FluxC-Android pull request #2124
Opened 2021-09-18 15:57 UTC by dnalves

### Description

We wanna provide users the possibility to [mark their posts as sticky](https://wordpress.org/support/article/sticky-posts/) (the same is already present in iOS and Web).
This PR is the first part needed to fix https://github.com/wordpress-mobile/WordPress-Android/issues/7953. 

It adds the field `mSticky` to the PostModel. This field is already present in the `PostWPComRestResponse`, so it was already being fetched from the API, we're just populating the model with its value

### Test

Make sure the classes are correctly generated by running `./gradlew fluxc:build`

2021-09-20 03:36 UTC, jd-alexander commented
@dnalves Thanks for the work here! I am going to be doing a review of this PR once the changes have been integrated with the associated WP Android PR wordpress-mobile/WordPress-Android#7953 To get around the `mobile-secrets` issue I created a PR using my credentials here https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2126 This PR generated a `FluxC` artifact with the version of `2126-25f36177560bf1b903612ee6ea8a95e9b15dd860` You can utilize this within WP-Android for your testing. 

As you can see on the PR I created the `Mocked Connected Tests` passed successfully 😉  

Let me know if you have any other questions. Thanks!

2021-09-20 04:55 UTC, jd-alexander commented on fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
> +                162 -> migrate(version) {
Thanks for doing this migration @dnalves Along with this migration, the database version has to be bumped here :) 
https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/b266da9cb9fe0d12bf452c039f08b5157ed82009/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt#L32

2021-09-20 07:31 UTC, dnalves commented on fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
> +                162 -> migrate(version) {
Oh, my bad. I didn't realize there was already a release with the version 162. I just pushed the fix :D

2021-09-21 10:19 UTC, jd-alexander requested changes
@dnalves I would have preferred if the work was in a branch of its own. What do you think?

2021-09-21 11:28 UTC, dnalves commented
> @dnalves I would have preferred if the work here was in a branch of its own rather than `develop`. What do you think?

Yes, I agree. I messed up pushing directly to develop. I'll fix it

2021-09-21 11:41 UTC, dnalves commented
I created a new PR pointing to a branch (instead of my fork `develop`).
I'm closing this PR.

2021-09-21 11:41 UTC, closed without merging