Fetch site domains
wordpress-mobile/WordPress-FluxC-Android pull request #2130
Opened 2021-09-28 06:45 UTC by ravishanker

Fetch list of site domains for display on new domains dashboard

- Add a new action FETCH_DOMAINS
- Fetches domains for a given site from `sites/:siteId/domains` endpoint

2021-09-29 17:39 UTC, renanferrari requested changes
Thanks for the changes! I've tested this with the WPAndroid PR and it seems to work as expected.

The code also looks good, but I left a comment below with a few suggestions.

2021-09-29 17:39 UTC, renanferrari commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
> +            FETCHED_DOMAINS -> handleFetchedSiteDomains(action.payload as FetchedDomainsPayload)
Since we're introducing a new call, we should probably replace `EventBus` usage with Coroutines, as per [the new architecture guidelines](https://github.com/wordpress-mobile/WordPress-FluxC-Android/wiki/Architecture), unless we really need it for some reason (I don't think we do in this case, but let me know if I'm missing something). 

After that's done, I'd also recommend:
- Wrapping the new method in the store with [`coroutineEngine.withDefaultContext`]( https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f6351af24f45379f96013ee4b44fe002220c385/fluxc/src/main/java/org/wordpress/android/fluxc/tools/CoroutineEngine.kt#L20-L28) to add some extra logging.
- Adding some tests. Doesn't need to be super comprehensive, but anything is better than none in this case 😉

2021-09-30 07:37 UTC, ravishanker commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
> +            FETCHED_DOMAINS -> handleFetchedSiteDomains(action.payload as FetchedDomainsPayload)
Thanks @renanferrari for a great suggestion as always.  Refactored to use coroutines, also added tests.  I was indeed feeling weird using EventBus 😏  Thank you.

2021-09-30 18:00 UTC, renanferrari reviewed
Thanks for the changes! Coroutines makes everything look so much better, doesn't it? 😄

I still left a couple of suggestions below, but other than that, this is pretty much good to go.

2021-09-30 18:00 UTC, renanferrari commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
> +            }
I'd actually just remove this too. We want to call the `fetchSiteDomains` function directly, so we shouldn't need to dispatch an action to use it. The reason other functions in this class do it this way is that they are trying to maintain backward compatibility.

Then you can move the `coroutineEngine` call inside the `fetchSiteDomains` function and use `withDefaultContext` instead of `launch`, similar to how we do it on the [`SiteOptionsStore`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/d32de86947dea4d0bc1b6ea247eb10fa73cc2777/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteOptionsStore.kt), for example.

Makes sense?

2021-10-01 06:27 UTC, ravishanker commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
> +            }
@renanferrari Thanks again.  It certainly does makes sense to go all the way.  Updated 👍

2021-10-01 16:08 UTC, renanferrari approved these changes
@ravishanker Thank you for all the changes! It's looking great now.

2021-10-01 16:08 UTC, renanferrari commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
> +        return wpComGsonRequestBuilder.syncGetRequest(this, url, mapOf(), DomainsResponse::class.java)
Nice cleanup! 👍

2021-10-01 16:09 UTC, merged