Jetpack CP: Add Jetpack-tunneled plugins-related functionalities.
wordpress-mobile/WordPress-FluxC-Android pull request #2164
Opened 2021-10-26 10:33 UTC by hafizrahman

## PR Description

This PR is adding functionalities to:
-  Install a plugin,
- Fetch a plugin's information
  
to .org sites that are connected using Jetpack Connection Package.

## To Test

1. Prepare a site connected with Jetpack CP. An easy way is to start a .org site, don't install Jetpack, and instead install Jetpack Backup plugin. Open the plugin's setting and connect it to your wpcom account.
2. Open Example app, then sign in to your wpcom account.
3. Go to "Plugins", then select the site created on step 1.
4. Use the "Install and activate a plugin" button and try installing a plugin. You will need to enter a plugin's slug, which is the `http://wordpress.org/support/plugin/<SLUG>` part on the Plugin Directory. Observe the log and ensure it says the plugin is installed and activated.
5. Use the "Fetch a plugin from site" button. Try fetching for `jetpack-backup/jetpack-backup`, and observe the log. It will show the plugin's name and description.

Extra: you can also use Flipper to observe the network calls on both buttons's action and check the request/response there.

2021-10-27 06:58 UTC, wzieba commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginJetpackTunnelRestClient.kt
> +                        dispatcher.dispatch(PluginActionBuilder.newFetchedSitePluginAction(payload))
hi @hafizrahman and @hichamboushaba ! 👋 I hope you don't mind jumping into your PRs with one comment but, [as Event Bus is a deprecated](https://github.com/wordpress-mobile/WordPress-FluxC-Android/wiki/Architecture), would you mind to change those new RestClients (`PluginJetpackTunnelRestClient` and `WPV2MediaRestClient` in #2163 ) to not use `Dispatcher` to communicate?

You could use coroutines like e.g. in [CommentsRestClient](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/766e0ae544de5d8b5e5d769d27f6bbb54bdf4f1d/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/stats/insights/CommentsRestClient.kt) or [AddonsRestClient](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/329454c58c643c5e1d50ee5c6e669422614a0698/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/addons/AddOnsRestClient.kt).

WDYT?

2021-10-27 07:25 UTC, hafizrahman commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginJetpackTunnelRestClient.kt
> +                        dispatcher.dispatch(PluginActionBuilder.newFetchedSitePluginAction(payload))
👋🏼  @wzieba Thank you for your suggestion! Personally the coroutines way is simpler and easier to understand for me, and I would have loved to use it here. In fact if you check [the first commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2164/commits/24d6cffb681a53602925e76cddb4d9f0ba585abc), you can see that my first iteration in the rest client already used coroutines.

However, the rest client is used to add functionalities to the existing `PluginStore`, that already exclusively uses EventBus. For the install plugin case, for example, the `PluginStore` already has a function that deals with installing plugin on:
- a wpcom site,
- a .org site with Jetpack plugin

And now this PR adds another case, to install to a .org site with Jetpack CP plugins.

I discussed this quite a bit with @hichamboushaba and we thought this would be the way to go for now. In the near future, the `PluginStore` and its related rest clients will have to be rewritten to not use Event Bus anymore.

2021-10-27 07:29 UTC, wzieba commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginJetpackTunnelRestClient.kt
> +                        dispatcher.dispatch(PluginActionBuilder.newFetchedSitePluginAction(payload))
Ok, gotcha, thank you @hafizrahman for more context and thank you and @hichamboushaba for discussing this! 🙌 . 

> we thought this would be the way to go for now. In the near future, the PluginStore and its related rest clients will have to be rewritten to not use Event Bus anymore.

sounds good!

2021-10-27 11:35 UTC, hichamboushaba requested changes
Really great work @hafizrahman, the functionality works well.

I left some comments for discussion

2021-10-27 11:35 UTC, hichamboushaba commented on example/src/main/java/org/wordpress/android/fluxc/example/PluginsFragment.kt
> +class PluginsFragment : StoreSelectingFragment() {
Inhereting from `StoreSelectingFragment` would make this fragment compatible with Woo fragments only, for better compatibility, you can probably add the button yourself to the layout, and use `showSiteSelectorDialog` to handle the logic of the selected site by yourself, WDYT?

2021-10-27 11:35 UTC, hichamboushaba commented on fluxc-processor/src/main/resources/wp-api-endpoints.txt
> +/plugins/<slug>#String
I would rename `slug` on this context to `name` to align with the rest of `PluginStore` logic, and the `SitePluginModel`.
This would also make the parameter in `fetchPlugin` clearer, without needing the explanation on this being different than the `slug`.

2021-10-27 11:35 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginJetpackTunnelRestClient.kt
> +            name = response.name
The name in the database matches the `plugin` field, while the `displayName` is what matches the `name` field, check the existing mapping we have now: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/abaefb3ae628cec6080ccf4be8ce523ce69ce2d2/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/plugin/PluginWPAPIRestClient.kt#L119-L132

I would also extract this logic and put it in a common place, for example in the `PluginResponseModel` file as an extension, to reuse the same logic in both places.

2021-10-27 11:35 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
> +        public FetchSitePluginPayload(SiteModel site, String slug) {
Same as above, I would rename the `slug` parameter, to make it clear this is not a slug, to align with `ConfigureSitePluginPayload`, you can call it `pluginName`.

2021-10-27 11:35 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
> +        if (payload.site.isJetpackCPConnected()) {
This can work for all jetpack connected sites, so IMO we should do two things here:
1. Update the condition to allow it to work for Jetpack sites too.
2. Add an else that falls back to using `fetchWPOrgPlugin` for the other cases, because the name `FETCH_SITE_PLUGIN` is generic.

2021-10-27 11:35 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
>          } else {
The chaining of those conditions will be broken once https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2163 is merged, and the cause is that there is a bug right now that makes jetpack CP sites return `true` when we check `isUsingWpComRestApi`, it's fixed here: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2163/files#diff-ac504807ac3755802bc839947ec85b4b045a906264eaf35ab97885016704df8aR1010-R1012

So to fix this, you need to move the check `isJetpackCPConnected` above the condition `if (!payload.site.isUsingWpComRestApi())`

2021-10-28 09:50 UTC, hafizrahman commented on example/src/main/java/org/wordpress/android/fluxc/example/PluginsFragment.kt
> +class PluginsFragment : StoreSelectingFragment() {
Yup! I also realized from your recent PR how you did it for media upload test. Will change it.

2021-10-28 09:57 UTC, hafizrahman commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
>          } else {
That makes sense, thanks!

Aside: How do you generate a permalink to a / some line of codes in the diff of a PR like that? I've been trying to figure that out for a while.

2021-10-28 10:03 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
>          } else {
> How do you generate a permalink to a / some line of codes in the diff of a PR like that? I've been trying to figure that out for a while.

When you select the lines (by clicking on the line numbers and swiping or using the shift key), then the URL in the address bar gets updated, you just need to copy it, and it will contain the parameter of the highlighted lines.

2021-10-29 10:30 UTC, hafizrahman commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
> +        if (payload.site.isJetpackCPConnected()) {
> Add an else that falls back to using fetchWPOrgPlugin for the other cases, because the name FETCH_SITE_PLUGIN is generic.

My purpose for this method is more to allow checking whether a plugin exists on a site, plus its current state (version, is it active or not, etc). The fallback will fetch a plugin's information from the repository. The informations from repository ([example here for Akismet](https://api.wordpress.org/plugins/info/1.0/akismet.json)) are different and seems to be for different purposes, it's more for the plugin's status in the repo (like ratings, changelogs).

What would you suggest in this case? I feel like probably `fetchSitePlugin()` might not be a clear enough name for its purpose.

2021-10-29 10:32 UTC, hafizrahman commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
>          } else {
Woah nice, thanks for that!

2021-10-29 10:35 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
> +        if (payload.site.isJetpackCPConnected()) {
OK, I see, `fetchWPOrgPlugin` is different.

So for our case, maybe we can rename the function and payload to something that let's us know this is for Jetpack sites: `fetchPluginForJetpackSite`, and just remove the condition on `isJetpackCPConnected` to let it work for other jetpack connected sites, WDYT?

2021-10-29 10:37 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginJetpackTunnelRestClient.kt
> +     * by the `GET wp/v2/plugins` endpoint. For example, for Jetpack, the correct value should be `jetpack/jetpack`.
I think this comment can be simplified now, we don't need to mention that it's different from the `slug`, since they don't have the same name anymore 🙂

2021-10-29 10:37 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginJetpackTunnelRestClient.kt
> +     * by the `GET wp/v2/plugins` endpoint. For example, for Jetpack, the correct value should be `jetpack/jetpack`.
Same as above.

2021-10-31 01:29 UTC, hafizrahman commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
> +        if (payload.site.isJetpackCPConnected()) {
Great suggestion, thank you. I've made the changes.

2021-11-03 03:18 UTC, hafizrahman commented
This is ready for another round of review @hichamboushaba Thank you!

2021-11-03 13:35 UTC, hichamboushaba reviewed
The changes looks good, I just left one last comment 🙂

2021-11-03 13:35 UTC, hichamboushaba commented on fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java
> +        if (payload.site.isJetpackConnected()) {
This fetch should work also for Jetpack CP connected sites, no?
When I said "just remove the condition on isJetpackCPConnected to let it work for other jetpack connected sites", I meant let the client check on this, now that you added the error `NOT_JETPACK_SITE`, I think the condition should be: "payload.site.isJetpackConnected || payload.site.isJetpackCPConnected", WDYT?

2021-11-03 13:49 UTC, hichamboushaba commented on example/src/main/java/org/wordpress/android/fluxc/example/PluginsFragment.kt
> +                showSingleLineDialog(activity, "Enter a plugin slug.") { pluginSlugText ->
A small nitpick too, should we say here "Enter the plugin name" instead?

2021-11-04 11:50 UTC, hafizrahman commented on example/src/main/java/org/wordpress/android/fluxc/example/PluginsFragment.kt
> +                showSingleLineDialog(activity, "Enter a plugin slug.") { pluginSlugText ->
Thanks! I missed this part.

2021-11-05 10:27 UTC, hichamboushaba approved these changes
Great job @hafizrahman 💯

2021-11-05 10:27 UTC, merged