Migrate newUpdateProductReviewStatusAction to a suspend function
wordpress-mobile/WordPress-FluxC-Android pull request #2271
Opened 2022-02-07 20:18 UTC by atomtec

Closes: #[5647](https://github.com/woocommerce/woocommerce-android/issues/5647) . This is a dependency in FluxC for the main fix 

**Description**

The main change for  5647 is to decouple the   tight coupling between ReviewDetailFragment and ReviewListFragment. As one of the item for the same newUpdateProductReviewStatusAction was also required to be migrated to suspend function. This will allow removal of EventBus from the class implementing the logic of moderation.

**Changes** 
Migrate the function to suspend
Update the tests

2022-02-08 18:21 UTC, hichamboushaba requested changes
Nice work @atomtec 💯

But the PR is not ready for merge yet, there are still usages of the old API in the tests (check those [lines](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e9da3c36c3b82591ab395b724b935bb2a9fa3a13/example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCProductTest.kt#L479-L495))

And it would be good to remove the unused `Actions` now that we migrated everything to coroutines.

And one remark regarding the commit messages, please try to put some good expressive messages, it would be better to avoid messages like "first one" 🙏

2022-02-08 21:55 UTC, atomtec commented
> Nice work @atomtec 100
> 
> But the PR is not ready for merge yet, there are still usages of the old API in the tests (check those [lines](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e9da3c36c3b82591ab395b724b935bb2a9fa3a13/example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_WCProductTest.kt#L479-L495))
Yup
> 
> And it would be good to remove the unused `Actions` now that we migrated everything to coroutines.
Yes missed that 
> 
> And one remark regarding the commit messages, please try to put some good expressive messages, it would be better to avoid messages like "first one" pray
Ahh !! thanks for pointing out I was initially planning this as temp branch so was not careful there . Will keep in mind.

2022-02-09 16:31 UTC, hichamboushaba approved these changes
Nice work @atomtec, I won't merge this until the WCAndroid's PR is ready.

2022-02-09 16:31 UTC, hichamboushaba commented on example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_WCProductsTest.kt
> +        Unit
np, another way to fix this would be to explicitly specify the return type on the function's signature.

2022-02-21 12:16 UTC, hichamboushaba commented
Thanks again @atomtec, but since we can't merge this now without the WCAndroid changes, I'm closing this PR for now.

2022-02-21 12:16 UTC, closed without merging