Coupons - Paging support
wordpress-mobile/WordPress-FluxC-Android pull request #2348
Opened 2022-04-08 08:24 UTC by 0nko

This PR adds paging support to for fetching coupons. 

**To test:**
1. Make sure your test store has > 2 coupons
2. Start the example app and go to Woo -> Coupons
3. Tap on the Fetch coupons button
4. Notice the 1st page of 2 coupons is fetched
5. Keep tapping the button, the list of fetched coupons will grow
6. When all coupons are fetched, notice the button gets disabled

2022-04-11 09:24 UTC, hafizrahman commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/CouponStore.kt
> +                        }
Nice 👍🏼

2022-04-11 09:50 UTC, hafizrahman commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/CouponStore.kt
> +    // Returns a boolean indicating whether more coupons can be fetched
Thanks for adding this!

2022-04-11 09:51 UTC, hafizrahman requested changes, later dismissed
Code looks good to me! There's now 5 failed tests in `CouponStoreTest`, I think we can merge once those are fixed.

2022-04-11 16:11 UTC, hichamboushaba reviewed
Works well, I left just two comments about the usage of `Dispatchers.IO`.

2022-04-11 16:11 UTC, hichamboushaba commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/CouponStore.kt
> +            .flowOn(Dispatchers.IO)
Room uses its own internal dispatcher, there is no need on specifying a different dispatcher here.

2022-04-11 16:11 UTC, hichamboushaba commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/CouponStore.kt
> +            .flowOn(Dispatchers.IO)
Same as above.

2022-04-12 09:38 UTC, 0nko commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/CouponStore.kt
> +            .flowOn(Dispatchers.IO)
Good call.

2022-04-13 14:50 UTC, hichamboushaba approved these changes
Looks good @0nko, I left two np comments, but nothing blocking.

2022-04-13 14:50 UTC, hichamboushaba commented on example/src/test/java/org/wordpress/android/fluxc/store/CouponStoreTest.kt
> +    private suspend fun mockTransaction() {
np, another way instead of having a separate function here, would be to use the `mock` function for mocking instead of the annotation, then replace the code with:
```kotlin
    private val transactionExecutor: TransactionExecutor = mock {
        val blockArg1 = argumentCaptor<suspend () -> Unit>()
        onBlocking { executeInTransaction(blockArg1.capture()) }.then {
            TEST_SCOPE.launch {
                blockArg1.lastValue.invoke()
            }
        }
    }
```

2022-04-13 14:50 UTC, hichamboushaba commented on example/src/test/java/org/wordpress/android/fluxc/store/CouponStoreTest.kt
> +            TEST_SCOPE.launch {
np, I would prefer to use runBlocking here to make sure the result of the blockArg1 is returned in the mocked version, which would match the behavior of executeInTransaction.
I wouldn't worry about any delays to be caused by runBlocking, since the functions we call in tests here are just not really blocking.

2022-04-13 17:00 UTC, 0nko commented on example/src/test/java/org/wordpress/android/fluxc/store/CouponStoreTest.kt
> +    private suspend fun mockTransaction() {
This is good, thanks for the tip!

2022-04-13 17:28 UTC, hichamboushaba approved these changes
Looks good, thanks @0nko

2022-04-13 17:29 UTC, merged

2022-04-14 08:54 UTC, hafizrahman commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/CouponStore.kt
> +            .flowOn(Dispatchers.IO)
TIL!