[Issue-2320] Variations batuch update: example app
wordpress-mobile/WordPress-FluxC-Android pull request #2374
Opened 2022-04-30 12:16 UTC by samiuelson

**This PR updates `example` to allow testing variations batch update. It's based on the other [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2367) which introduced batch variations update feature in `WcProductStore`. It is the last implementation part of the https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2320 issue.** 

#### 🎯 Summary
This PR updates `example` app to allow testing variations batch update feature.

#### 🛠 Implementation details
* Added `WooBatchUpdateVariationsFragment`, accessible from `WooProductsFragment`.

#### 📱 Visual changes

<img src="https://user-images.githubusercontent.com/4527432/166104912-4a28e5eb-defb-4474-8801-5742c2fb975e.png" height="512"/> <img src="https://user-images.githubusercontent.com/4527432/166104917-0625fee8-e022-4717-b3b9-59a1d7c90fb1.png" height="512"/>

#### 🧪 Testing
Run the example app and:
1. Navigate to `Batch Update Variations` screen.  
2. Enter product id, and ids of variations (comma-separated).
3. Click `Set up product id and variations ids` button to validate ids and check if they exist in DB.
4. Fill in the form below with the data you want to batch update the variations.
5. Click the button on the bottom.

In-app logs should inform about the product/variations validation errors and the batch update operation result.

#### 🧭 Roadmap
Once this PR is merged, there will be an aggregate PR raised containing the previous [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2367) and closing the https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2320 issue.

2022-05-04 13:44 UTC, 0nko requested changes
I've played around with the app and the batch update working well (apart for some small things) :+1:. 

I left some comments left in the code and I noticed something about the sale dates -- the layout contains a date selector for non-GMT date but only an edit text for GMT date. I don't think it's necessary to have both here. Recently there was a discussion about what date to use, we concluded that the non-GMT (store date) probably makes most sense for the store owner. The GMT is then automatically offset and updated.

2022-05-04 13:44 UTC, 0nko commented on example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooBatchUpdateVariationsFragment.kt
> +            with(stock_quantity.getText()) {
This is a duplicate of the previous change. I think you meant to update the stock status here.

2022-05-04 13:44 UTC, 0nko commented on example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooBatchUpdateVariationsFragment.kt
> +                if (isNotEmpty()) variationsUpdatePayloadBuilder.dimensions(this)
This won't work unless you manually construct a JSON string with the right properties. See the [Dimensions](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) property definition for more details.

2022-05-04 14:04 UTC, samiuelson commented on example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooBatchUpdateVariationsFragment.kt
> +            with(stock_quantity.getText()) {
It's just a duplicated code. Stock status is updated using a ListSelectorDialog ([here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2374/files#diff-9bfe9cd7927b14a1c1ad164783ea1bcb3212ca35c60c015d7e2b541d2901eb27R217)). Fixed with [4055ce9](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2374/commits/4055ce9b2653540c59e0c72c076e57dc80ac2dd0).

2022-05-04 14:09 UTC, samiuelson commented on example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooBatchUpdateVariationsFragment.kt
> +                if (isNotEmpty()) variationsUpdatePayloadBuilder.dimensions(this)
Good catch. I think the right approach will be to update `BatchUpdateVariationsPayload.Builder::dimensions` method to take `length`, `width`, and `height` args instead of a single String and build `dimensions` object internally. What do you think @0nko?

2022-05-04 14:12 UTC, samiuelson commented
> I've played around with the app and the batch update working well (apart for some small things) 👍.
> 
> I left some comments left in the code and I noticed something about the sale dates -- the layout contains a date selector for non-GMT date but only an edit text for GMT date. I don't think it's necessary to have both here. Recently there was a discussion about what date to use, we concluded that the non-GMT (store date) probably makes most sense for the store owner. The GMT is then automatically offset and updated.

@Onko thanks for review!
Regarding GMT date, do you think we should remove it from the `BatchUpdateVariationsPayload.Builder` too or just from the example app?

2022-05-04 14:51 UTC, 0nko commented
> Regarding GMT date, do you think we should remove it from the BatchUpdateVariationsPayload.Builder too or just from the example app?

I think you can remove it there too.

2022-05-04 14:53 UTC, 0nko commented on example/src/main/java/org/wordpress/android/fluxc/example/ui/products/WooBatchUpdateVariationsFragment.kt
> +                if (isNotEmpty()) variationsUpdatePayloadBuilder.dimensions(this)
Yeah, that sounds reasonable.

2022-05-04 16:38 UTC, samiuelson commented
Alright, I've added the fixes:
* Dimensions property is revised to the correct model. I've tested this and the dimensions update works fine now 👍🏼 
* GMT sale dates handling is removed both from the payload and example app.

2022-05-05 10:10 UTC, 0nko approved these changes
Nice job!

2022-05-05 10:10 UTC, merged

2022-05-05 10:56 UTC, samiuelson commented
> Nice job!

🙌 Thanks for review!