Add PUT/POST endpoint in fluxc to support enabling/disabling Cash on Delivery as payment method
wordpress-mobile/WordPress-FluxC-Android pull request #2492
Opened 2022-08-10 14:11 UTC by rossanafmenezes

Closes [woocommerce-android/issues/7141](https://github.com/woocommerce/woocommerce-android/issues/7141)

This PR adds the endpoint functions to enable/disable cash on delivery from the Woo Mobile app and give the user the ability to change the Cash on Delivery title. 

Context: pdfdoF-167-p2

It also adds a new test file related to the gatewayRestClient.kt file and the equivalent tests for it.

2022-08-11 07:41 UTC, malinajirka requested changes
Thanks @rossanafmenezes! You are on the right path, but I noticed a couple of issues (⚠️). Moreover, I left some thoughts/nitpicks (🔍 💡 ) for you to consider - those don't require code changes, just think about them and try to apply them next time if they make sense to you. Thanks :)

2022-08-11 07:41 UTC, malinajirka commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        val url = WOOCOMMERCE.payment_gateways.gateway(title).pathV3
⚠️ This line is responsible for the construction of the URL. However, it seems we are including the user-facing title as part of the url.

For example, when the user sets the title to `Pay with a credit/debit card or cash upon delivery.`, the url we construct will be
`.../wc/v3/payment_gateways/Pay with a credit/debit card or cash in person./`. 


Since, the endpoint for disabling/enabling COD and changing the title is one and the same, we can re-use the code from line 58 - `val url = WOOCOMMERCE.payment_gateways.gateway(gatewayId.toString()).pathV3`. 

We could even go as far as merging `postPaymentGateway` and `postCashOnDeliveryTitle` into one method, perhaps called something like `updatePaymentGateway` - it's one endpoint, so having two separate methods for it feels slightly misleading. We'd just need to make sure to make the `title` parameter as optional so we post it to the server only when the user changes it. Wdyt?

2022-08-11 07:41 UTC, malinajirka commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        val params = mapOf("Cash on Delivery" to title)
⚠️ The `key` in the map is currently set to `Cash on Delivery`, however [according to the documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-payment-gateway) it seems the correct name for the `key` is `title`. I believe we might need to change this line to `mapOf("title" to title)`, wdyt?

2022-08-11 07:41 UTC, malinajirka commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        COD
🔍 Nitpick: Most devs who will be reading this code will realize, that COD means Cash On Delivery. However, probably not all of them. I think we might consider making it a bit more explicit/readable by calling the enum CASH_ON_DELIVERY and setting a key to `cod`. Wdyt?

```
enum class GatewayId(val apiKey: String) {
        CASH_ON_DELIVERY("cod")
    }
```

2022-08-11 07:41 UTC, malinajirka commented on example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/GatewayRestClientTest.kt
> +    fun `given success response, when post gateway, return success`() {
💡 The tests in this class feel quite complicated considering what they actually test. Unless I'm missing something we are mocking essentially everything. The tests only test that when a success is returned the response is stored into `WooPayload.result` and when a failure is returned the response is stored into `WooPayload.error`.

Perhaps, we could simplify them to the following format to make it more explicit what they actually test:

```
@Test
    fun `given success response, when post gateway, return success`() {
        runBlocking {
            whenever(
                jetpackTunnelGsonRequestBuilder.syncPostRequest(
                    any(),
                    any(),
                    any(),
                    any(),
                    any<Class<GatewayRestClient.GatewayResponse>>()
                )
            ).thenReturn(
                JetpackTunnelGsonRequestBuilder.JetpackResponse.JetpackSuccess(mock())
            )

            val actualResponse = gatewayRestClient.postPaymentGateway(
                SiteModel(),
                COD,
                enabled = false
            )

            Assertions.assertThat(actualResponse.isError).isFalse
            Assertions.assertThat(actualResponse.result).isNotNull
        }
    }

    @Test
    fun `given error response, when post gateway, return error`() {
        runBlocking {
            val expectedError = mock<WPComGsonNetworkError>().apply {
                type = mock()
            }
            whenever(
                jetpackTunnelGsonRequestBuilder.syncPostRequest(
                    any(),
                    any(),
                    any(),
                    any(),
                    any<Class<GatewayRestClient.GatewayResponse>>(),
                )
            ).thenReturn(
                JetpackTunnelGsonRequestBuilder.JetpackResponse.JetpackError(expectedError)
            )

            val actualResponse = gatewayRestClient.postPaymentGateway(
                SiteModel(),
                COD,
                enabled = true
            )

            Assertions.assertThat(actualResponse.isError).isTrue
            Assertions.assertThat(actualResponse.error).isNotNull
        }
    }
```

Wdyt?


P.S. In general, I personally prefer the Mocked tests over unit tests for rest clients. The mocked tests actually test the code works and test the json parsing works. Moreover, they serve as a documentation for possible responses from the endpoint. Something similar to what we have in `MockedStack_InPersonPaymentsTest`. But we can do that in another PR later, it's not something we need to do. Wdyt?

2022-08-11 13:27 UTC, rossanafmenezes commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        COD
💯  Changed

2022-08-11 14:22 UTC, rossanafmenezes commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        val url = WOOCOMMERCE.payment_gateways.gateway(title).pathV3
[I had originally done only one method](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2492/commits/ecc30907f43ca62518ea2f8f66447ba2245a30d3) (and renamed it after) but had not made the title optional (sorry, it did not cross my mind) so it would not work the way I did and ended up splitting it into two. 

cc: @AnirudhBhat 

When you say "make it optional" do you mean making the title nullable?

2022-08-11 14:25 UTC, rossanafmenezes commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        val params = mapOf("Cash on Delivery" to title)
Absolutely. Sorry about that.

2022-08-11 14:40 UTC, malinajirka commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        val url = WOOCOMMERCE.payment_gateways.gateway(title).pathV3
No reason to apologize :).

> When you say "make it optional" do you mean making the title nullable?

Make it nullable and default value `null` => when the value is `null` do not send the `enabled`/`title` parameter to the server so the server doesn't change the setting. Something like this:

```
 suspend fun ...(
        site: SiteModel,
        gatewayId: GatewayId,
        enabled: Boolean? = null,
        title: String? = null
    ) ...
    ...
      mutableMapOf<String, Any>().apply {
            enabled?.let { put("enabled", enabled) }
            title?.let { put("title", title) }
        }
```

2022-08-11 14:46 UTC, rossanafmenezes commented on example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/GatewayRestClientTest.kt
> +    fun `given success response, when post gateway, return success`() {
I had also started with a [mocked test at first ](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2492/commits/8a7a3a960165ea9ebae886e911ad90dfd92af114) but I got a bit lost. I will simplify the existing test and I can add an issue to work on the mock tests to replace these ones

2022-08-12 03:38 UTC, AnirudhBhat commented
@rossanafmenezes Thank you so much for working on this! I've got a small comment.

I see that you have added the endpoint implementation in `GatewayRestClient` class. AFAIU, the WooCommerce module doesn't touch the client classes directly; all communication happens via the store class which takes care of thread switching. In this case, it would be the `WCGatewayStore` class. 

What do you think about adding methods in `WCGatewayStore` class that in turn calls the methods from the `GatewayRestClient` class? 

This can be a separate PR as well. Just wanted to bring this to your attention. Sorry I missed noticing this during our initial discussion.

2022-08-12 12:17 UTC, rossanafmenezes commented
Hi @AnirudhBhat 

Thanks for the input :) 

> What do you think about adding methods in WCGatewayStore class that in turn calls the methods from the GatewayRestClient class?

While  I understand this is usually addressed on the same PR, the plan was to do that on a separate PR this time. :)

2022-08-12 12:59 UTC, rossanafmenezes commented on plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/gateways/GatewayRestClient.kt
> +        val url = WOOCOMMERCE.payment_gateways.gateway(title).pathV3
Great. Thank you. I have consolidated both methods into one

2022-08-14 06:15 UTC, malinajirka commented on example/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/GatewayRestClientTest.kt
> +    fun `given success response, when post gateway, return success`() {
Thanks! I wouldn't replace them, they both add some value - but adding the mocked tests in a follow up PR would be awesome. Thank you 🙇

2022-08-14 06:16 UTC, malinajirka approved these changes
LGTM, great job, thank you 🙇 ! 🚢

2022-08-14 06:16 UTC, merged