Analytics Performance: Add access to revenue stats from ID query
wordpress-mobile/WordPress-FluxC-Android pull request #2785
Opened 2023-07-24 20:58 UTC by ThomazFB

2023-07-27 16:09 UTC, atorresveiga approved these changes
Great work Thomaz! The code looks good and is working as expected.

LGTM! :shipit:

2023-07-27 16:11 UTC, atorresveiga commented on fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
> +                    db.execSQL("ALTER TABLE WCRevenueStatsModel ADD RANGE_ID INTEGER")
Nice!

2023-07-27 16:24 UTC, atorresveiga requested changes
I almost miss something 🤦 

You must replace 191 ->` migrate(version)` to `migrateAddOn(ADDON_WOOCOMMERCE, version)` otherwise the WP app will crash because it doesn't have the WCRevenueStatsModel table

2023-07-28 00:02 UTC, ThomazFB commented
Wow, sorry that I forgot about this @atorresveiga, thank you so much for finding it in time to avoid a huge problem 😬 It's fixed now!

2023-07-28 05:52 UTC, atorresveiga approved these changes
Awesome work Thomaz! Using the new revenueRangeId is a great addition that will made our life easier when working with the stats.

LGTM! :shipit:

2023-07-28 09:36 UTC, merged