[Nullability Annotations to Java Classes] Add Missing Nullability Annotations to `TaxonomyXMLRPCClient` (`safe`)
wordpress-mobile/WordPress-FluxC-Android pull request #2866
Opened 2023-10-09 14:10 UTC by ParaskP7

TODO

2023-10-10 16:00 UTC, irfano requested changes
I've tested the PR on the FluxC example app and Jetpack (but not on WP to save time). I haven't noticed any issues. 🟢
I only have a comment for you to address.

2023-10-10 16:00 UTC, irfano commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/taxonomy/TaxonomyXMLRPCClient.java
>                      }
⚠️  Before, the payload constructor was also getting `terms` and `site`. `payload` has lost these arguments here. We should revert this change.

2023-10-11 08:16 UTC, ParaskP7 commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/taxonomy/TaxonomyXMLRPCClient.java
>                      }
👋 @irfano, thanks for this comment and for being thorough with the reviews, this always so much appreciated! ❤️  

However, this was actually done by design and I think it is best we keep this change as is, let me explain:

1. Initial problem that forced me into that change was the fact that the `payload` was being build with the nullable `terms` model (see [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/ba92dd07fbcc2987c91a8d8a37fd5952881d3286/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/taxonomy/TaxonomyXMLRPCClient.java#L123)).
2. Since this `payload` cannot be used for when `terms == null` I had to use the error `payload` instead. To my understanding there was a potential NPE here that got averted.
3. I then researched if this error payload needs to `terms` or `site` arguments and noticed it doesn't (see [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/ba92dd07fbcc2987c91a8d8a37fd5952881d3286/fluxc/src/main/java/org/wordpress/android/fluxc/store/TaxonomyStore.java#L343-L345)). From this code reference I just shared you will noticed that the error `payload` only  needs a `taxonomyName` to emit the change and thus it turns out that both, the `terms` and `site` arguments are actually unused and thus not needed.
 
Let me know your thoughts. 🙏 

FYI: You can follow `TaxonomyActionBuilder.newFetchedTermsAction(payload)` and `TaxonomyAction.FETCHED_TERMS` to get to the bottom of this.

2023-10-11 08:18 UTC, ParaskP7 commented
👋 @irfano and thank you so much for reviewing, testing and commenting on this PR, you rock! 🙇 ❤️ 

FYI: I left [this comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2866#discussion_r1354367384) for your that hopefully clears-up [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2866#discussion_r1352795158) confusion on why I made that change.

2023-10-11 16:00 UTC, irfano commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/taxonomy/TaxonomyXMLRPCClient.java
>                      }
I understand. So, you've already conducted research on this. Great job! I agree with your comments. 👍🏻

2023-10-11 16:01 UTC, irfano approved these changes

2023-10-11 16:02 UTC, merged

2023-10-12 07:24 UTC, ParaskP7 commented on fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/taxonomy/TaxonomyXMLRPCClient.java
>                      }
Awesome, thanks for re-checking the logic @irfano ! 🙇

2023-10-12 07:24 UTC, ParaskP7 commented
Thanks for approving and merging this @irfano ! 🙇 ❤️ 🚀